
import javax.swing.JFileChooser;
import java.io.*;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author admin
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        /*tab2panel = new javax.swing.JPanel();
       jTabbedPane1.insertTab("tab2",null,tab2panel,null,1);*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser(new File("C:\\Users\\Pratheeksha\\Desktop\\FinalYearProject\\"));
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        graph = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
		jButton4 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jComboBox2 = new javax.swing.JComboBox();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1400, 725));

        jTabbedPane1.setPreferredSize(new java.awt.Dimension(698, 638));
		

        jPanel2.setAutoscrolls(true);
        jPanel2.setPreferredSize(new java.awt.Dimension(1400, 692));
		jPanel3.setAutoscrolls(true);
        jPanel3.setPreferredSize(new java.awt.Dimension(1400, 692));
        jTextField2.setText(" ");

        jButton1.setText("Choose input directory");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Voting Based", "Adjective Based", "Cue Based", "Other Parts-Of-Speech Based"}));
        jComboBox1.setName("Based on");
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jRadioButton1.setText("Full Document");
        jRadioButton1.setEnabled(false);
        jRadioButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton1MouseClicked(evt);
            }
        });

        jRadioButton2.setText("First Sentence");
        jRadioButton2.setEnabled(false);
        jRadioButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton2MouseClicked(evt);
            }
        });
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jRadioButton3.setText("Last Sentence");
        jRadioButton3.setEnabled(false);
        jRadioButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton3MouseClicked(evt);
            }
        });
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        jRadioButton4.setText("Significant Sentence");
        jRadioButton4.setEnabled(false);
        jRadioButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton4MouseClicked(evt);
            }
        });

        jRadioButton5.setText("First + Last + Significant");
        jRadioButton5.setEnabled(false);
        jRadioButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton5MouseClicked(evt);
            }
        });

        jLabel3.setText("Choose Method:");

        jLabel4.setText("Choose Input Type:");

        //graph.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AdjectiveCnt.jpg"))); // NOI18N
        graph.setMaximumSize(new java.awt.Dimension(1000, 480));
        graph.setPreferredSize(new java.awt.Dimension(800, 480));

        jButton2.setText("Get Graph");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jButton1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jButton2)
                                .addGap(41, 41, 41)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton2)
                                    .addComponent(jRadioButton5)
                                    .addComponent(jRadioButton1)
                                    .addComponent(jRadioButton3)
                                    .addComponent(jRadioButton4))
                                .addGap(0, 186, Short.MAX_VALUE)))))
                .addGap(51, 51, 51)
                .addComponent(graph, javax.swing.GroupLayout.PREFERRED_SIZE, 763, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(graph, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton5)
                        .addGap(83, 83, 83)
                        .addComponent(jButton2)))
                .addContainerGap(159, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Threshold vs Accuracy", jPanel2);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);
		jTextArea1.setText(" ");

        jTextField1.setText(" ");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Enter your text");

        jLabel2.setText("Result :");

        jButton3.setText("Get Result");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
				try
			{
                jButton3ActionPerformed(evt);
			}
			catch(Exception e)
			{
				System.out.println(e);
			}
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel2)
                        .addGap(48, 48, 48)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addComponent(jButton3)))
                .addContainerGap(929, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(447, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Classify User Input", jPanel1);

        //jPanel3.setPreferredSize(new java.awt.Dimension(500, 500));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Voting Based", "Adjective Based", "Cue Based", "Other Parts-Of-Speech Based" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jRadioButton6.setText("Full Document");
		jRadioButton6.setEnabled(false);
        jRadioButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton6MouseClicked(evt);
            }
        });

        jRadioButton7.setText("First Sentence");
		jRadioButton7.setEnabled(false);
        jRadioButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton7MouseClicked(evt);
            }
        });

        jRadioButton8.setText("Last Sentence");
		jRadioButton8.setEnabled(false);
        jRadioButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton8MouseClicked(evt);
            }
        });

        jRadioButton9.setText("Significant Sentence");
		jRadioButton9.setEnabled(false);
        jRadioButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton9MouseClicked(evt);
            }
        });
        jRadioButton10.setText("First + Last + Significant");
		jRadioButton10.setEnabled(false);
        jRadioButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton10MouseClicked(evt);
            }
        });
		
        jLabel5.setText("Choose Method:");

        jLabel6.setText("Choose Input Type:");

        jLabel8.setText(" ");
		
		jLabel8.setMaximumSize(new java.awt.Dimension(1000, 480));
        jLabel8.setPreferredSize(new java.awt.Dimension(680, 480));
		
		 jButton4.setText("Get Graph");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)))
                .addGap(49, 49, 49)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton6)
                            .addComponent(jLabel6))
                        .addContainerGap(1097, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton10)
                            .addComponent(jRadioButton9)
                            .addComponent(jRadioButton7)
                            .addComponent(jRadioButton8)
                            .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 646, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButton6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton10)
                        .addGap(68, 68, 68)
                        .addComponent(jButton4))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(107, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("No. Of Input Files vs MaxAccuracy", jPanel3);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        jRadioButton1.setEnabled(false);
        jRadioButton2.setEnabled(false);
        jRadioButton3.setEnabled(false);
        jRadioButton4.setEnabled(false);
        jRadioButton5.setEnabled(false);
        
        jRadioButton1.setSelected(false);
        jRadioButton2.setSelected(false);
        jRadioButton3.setSelected(false);
        jRadioButton4.setSelected(false);
        jRadioButton5.setSelected(false);
        
        String method = (String)jComboBox1.getSelectedItem();
        if(method.compareTo("Voting Based")==0)
        {
            Method = "Voting Based";
            jRadioButton1.setEnabled(true);
            jRadioButton2.setEnabled(true);
            jRadioButton3.setEnabled(true);
        }
        else if(method.compareTo("Adjective Based")==0)
        {
            Method = "Adjective Based";
            jRadioButton1.setEnabled(true);
            jRadioButton2.setEnabled(true);
            jRadioButton3.setEnabled(true);
            jRadioButton4.setEnabled(true);
            jRadioButton5.setEnabled(true);
         
        }
        else if(method.compareTo("Cue Based")==0)
        {
            Method = "Cue Based";
            jRadioButton1.setEnabled(true);
        }
        else if(method.compareTo("Other Parts-Of-Speech Based")==0)
        {
            Method = "Other Parts-Of-Speech Based";
            jRadioButton1.setEnabled(true);
            jRadioButton2.setEnabled(true);
            jRadioButton3.setEnabled(true);
            jRadioButton4.setEnabled(true);
            jRadioButton5.setEnabled(true);
        }
    }                                          

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        jFileChooser1.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);
        int rVal = jFileChooser1.showOpenDialog(jPanel2);
        if (rVal == javax.swing.JFileChooser.APPROVE_OPTION) {
            //filename.setText(c.getSelectedFile().getName());
            jTextField2.setText(jFileChooser1.getSelectedFile().getPath().toString());
        }
        if (rVal == javax.swing.JFileChooser.CANCEL_OPTION) {
            //filename.setText("You pressed cancel");
            jTextField2.setText("No directory chosen");
           
        }
    }                                        

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {                                      
        // TODO add your handling code here:
    }                                     

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        //set text as opinion or fact
    }                                           

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
		
    }                                             

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
		
		jRadioButton6.setEnabled(false);
        jRadioButton7.setEnabled(false);
        jRadioButton8.setEnabled(false);
        jRadioButton9.setEnabled(false);
        jRadioButton10.setEnabled(false);
        
        jRadioButton6.setSelected(false);
        jRadioButton7.setSelected(false);
        jRadioButton8.setSelected(false);
        jRadioButton9.setSelected(false);
        jRadioButton10.setSelected(false);
        
        String method = (String)jComboBox2.getSelectedItem();
        if(method.compareTo("Voting Based")==0)
        {
            Method2 = "Voting Based";
            jRadioButton6.setEnabled(true);
            jRadioButton7.setEnabled(true);
            jRadioButton8.setEnabled(true);
        }
        else if(method.compareTo("Adjective Based")==0)
        {
            Method2 = "Adjective Based";
            jRadioButton6.setEnabled(true);
            jRadioButton7.setEnabled(true);
            jRadioButton8.setEnabled(true);
            jRadioButton9.setEnabled(true);
            jRadioButton10.setEnabled(true);
         
        }
        else if(method.compareTo("Cue Based")==0)
        {
            Method2 = "Cue Based";
            jRadioButton6.setEnabled(true);
        }
        else if(method.compareTo("Other Parts-Of-Speech Based")==0)
        {
            Method2 = "Other Parts-Of-Speech Based";
            jRadioButton6.setEnabled(true);
            jRadioButton7.setEnabled(true);
            jRadioButton8.setEnabled(true);
            jRadioButton9.setEnabled(true);
            jRadioButton10.setEnabled(true);
        }
    }

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) throws IOException{
        // TODO add your handling code here:
		// TODO add your handling code here:
	String argument = jTextArea1.getText();
	if(argument.compareTo(" ")==0 || argument.length() == 0)
	{
	            jTextField1.setText("Enter your text");
				return;
	}
	String filename = "Tab2.txt";
	FileWriter file = new FileWriter(filename);
	file.write(argument);
	file.close();
	//String compile="javac ClassifyOpFact.java";
	String run = "java Basic.ClassifyOpFact "+(new File(filename).getAbsolutePath());
	System.out.println(run);
	
	/*try
            {

                Process proc = Runtime.getRuntime().exec(compile);
                try
                {
                    proc.waitFor();
					proc.getInputStream().close();
					proc.getOutputStream().close();
					proc.getErrorStream().close();
                }
                catch(Exception e)
                {
                    System.out.println(e);
                }
                proc.destroy();
            }
            catch(IOException e)
            {
                System.out.println(e);
                
            }*/
	
	try
            {

                Process proc = Runtime.getRuntime().exec(run);
                try
                {
                    proc.waitFor();
					proc.getInputStream().close();
					proc.getOutputStream().close();
					proc.getErrorStream().close();
                }
                catch(Exception e)
                {
                    System.out.println(e);
                }
				System.out.println("Run complete");
                proc.destroy();
            }
            catch(IOException e)
            {
                System.out.println(e);
                
            }
			String result = new BufferedReader((new FileReader("ClassifyOpFactResult.txt"))).readLine();
            jTextField1.setText(result);
    }
	
	    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
		String key = new String();
        key = Method2 + "," + inputType2;
        
        if(ht.containsKey(key))
        {
        String filename = ht.get(key).toString();
		javax.swing.ImageIcon icon;
		filename = filename.substring(6);
		if(filename.contains("Main"))
		{
			filename = filename.substring(0,filename.length()-4);
		}
		icon = new javax.swing.ImageIcon("graphs/"+filename+"Rec.JPG");
			jLabel8.setIcon(icon);
			}
		}

    private void jRadioButton1MouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        inputType = "Full Document";
        jRadioButton2.setSelected(false);
        jRadioButton3.setSelected(false);
        jRadioButton4.setSelected(false);
        jRadioButton5.setSelected(false);
    }

    private void jRadioButton2MouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        inputType = "First Sentence";
        jRadioButton1.setSelected(false);
        jRadioButton3.setSelected(false);
        jRadioButton4.setSelected(false);
        jRadioButton5.setSelected(false);
    }

    private void jRadioButton3MouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        inputType = "Last Sentence";
        jRadioButton1.setSelected(false);
        jRadioButton2.setSelected(false);
        jRadioButton4.setSelected(false);
        jRadioButton5.setSelected(false);
    }

    private void jRadioButton4MouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        inputType = "Significant Sentence";
        jRadioButton1.setSelected(false);
        jRadioButton2.setSelected(false);
        jRadioButton3.setSelected(false);  
        jRadioButton5.setSelected(false);
    }

    private void jRadioButton5MouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        inputType = "First + Last + Significant";
        jRadioButton1.setSelected(false);
        jRadioButton2.setSelected(false);
        jRadioButton3.setSelected(false);
        jRadioButton4.setSelected(false);
    }
	
	    private void jRadioButton6MouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        inputType2 = "Full Document";
        jRadioButton7.setSelected(false);
        jRadioButton8.setSelected(false);
        jRadioButton9.setSelected(false);
        jRadioButton10.setSelected(false);
    }
	
	    private void jRadioButton7MouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        inputType2 = "First Sentence";
        jRadioButton6.setSelected(false);
        jRadioButton8.setSelected(false);
        jRadioButton9.setSelected(false);
        jRadioButton10.setSelected(false);
    }
	
	    private void jRadioButton8MouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        inputType2 = "Last Sentence";
        jRadioButton7.setSelected(false);
        jRadioButton6.setSelected(false);
        jRadioButton9.setSelected(false);
        jRadioButton10.setSelected(false);
    }
	
	    private void jRadioButton9MouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        inputType2 = "Significant Sentence";
        jRadioButton7.setSelected(false);
        jRadioButton8.setSelected(false);
        jRadioButton6.setSelected(false);
        jRadioButton10.setSelected(false);
    }
	
	    private void jRadioButton10MouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        inputType2 = "First + Last + Significant";
        jRadioButton7.setSelected(false);
        jRadioButton8.setSelected(false);
        jRadioButton9.setSelected(false);
        jRadioButton6.setSelected(false);
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        //GetseletedItems from the combobox and radiobutton and concat
        //String  filename ht.get(concatenatedstring)
        String key = new String();
        key = Method + "," + inputType;
        if(jTextField2.getText().compareTo(" ")==0 || jTextField2.getText().length() == 0 || jTextField2.getText().compareTo("No directory chosen")==0)
		{
		jTextField2.setText("Choose a directory");
		return;
		}
        if(ht.containsKey(key))
        {
            String filename = ht.get(key).toString();
            String compile = "javac "+filename+".java";
            String run = "java "+filename+" "+jTextField2.getText()+"\\*.txt";
			if(filename.contains("Basic"))
			{
				filename = filename.substring(6);
				System.out.println(filename);
				if(filename.contains("Main"))
				{
					filename = filename.substring(0,filename.length()-4);
					
				}
			}
			String gnuplot = "C:\\Program Files\\gnuplot\\bin\\wgnuplot.exe " + "graphs/" + filename + ".gnu";
			System.out.println(gnuplot);
			javax.swing.ImageIcon icon;
			System.out.println(run);
            /*try
            {
            
                Process proc = Runtime.getRuntime().exec(compile);
                try
                {
                    proc.waitFor();
					proc.getInputStream().close();
					proc.getOutputStream().close();
					proc.getErrorStream().close();
                }
                catch(Exception e)
                {
                    System.out.println(e);
                }
				
                proc.destroy();
            }
            catch(IOException e)
            {
                System.out.println(e);
                
            }*/
            
            try
            {
                Process proc = Runtime.getRuntime().exec(run);
                try
                {
                    proc.waitFor();
					System.out.println("Run complete");
					proc.getInputStream().close();
					proc.getOutputStream().close();
					proc.getErrorStream().close();
                }
                catch(Exception e)
                {
                    System.out.println(e);
                }
                proc.destroy();
            }
            catch(IOException e)
            {
                System.out.println(e);
                
            }
			
			try
            {
                Process proc = Runtime.getRuntime().exec(gnuplot);
                try
                {
                    proc.waitFor();
					proc.getInputStream().close();
					proc.getOutputStream().close();
					proc.getErrorStream().close();
                }
                catch(Exception e)
                {
                    System.out.println(e);
                }
                proc.destroy();
            }
            catch(IOException e)
            {
                System.out.println(e);
                
            }
			icon = new javax.swing.ImageIcon("graphs/"+filename+".JPG");
			graph.setIcon(icon);
        }
             
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        ht = new java.util.Hashtable<String,String>();
        
        ht.put("Voting Based,Full Document","Basic.Threshold");
        ht.put("Voting Based,First Sentence","Basic.FirstSentenceV");
        ht.put("Voting Based,Last Sentence","Basic.lastSentenceV");
        
        ht.put("Adjective Based,Full Document","Basic.AdjectiveCnt");
        ht.put("Adjective Based,First Sentence","Basic.FirstSentenceMain");
        ht.put("Adjective Based,Last Sentence","Basic.lastSentenceMain");
        ht.put("Adjective Based,Significant Sentence","Basic.SignificantMain");
        ht.put("Adjective Based,First + Last + Significant","Basic.allmethod");
        
        ht.put("Cue Based,Full Document","Basic.CueBased");
        
        ht.put("Other Parts-Of-Speech Based,Full Document","Basic.OtherPOS");
        ht.put("Other Parts-Of-Speech Based,First Sentence","Basic.OtherPOSFirst");
        ht.put("Other Parts-Of-Speech Based,Last Sentence","Basic.OtherPOSLast");
        ht.put("Other Parts-Of-Speech Based,Significant Sentence","Basic.OtherPOSSig");
        ht.put("Other Parts-Of-Speech Based,First + Last + Significant","Basic.OtherPOSAll");
        
        
        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
        
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify
    private javax.swing.JLabel graph;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
	 private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration
    private String Method;
	private String Method2;
    private String inputType;
	private String inputType2;
    private static java.util.Hashtable<String,String> ht;
}

