javac -d . Basic\Threshold.java
javac -d . Basic\AdjectiveCnt.java
javac -d . Basic\FirstSentence.java
javac -d . Basic\lastSentence.java
javac -d . Basic\Significant.java
javac -d . Basic\lastSentenceV.java
javac -d . Basic\FirstSentenceV.java
javac -d . Basic\OtherPOS.java
javac -d . Basic\OtherPOSAll.java
javac -d . Basic\OtherPOSFirst.java
javac -d . Basic\OtherPOSLast.java
javac -d . Basic\OtherPOSSig.java
javac -d . Basic\CueBased.java
javac -d . Basic\ClassifyOpFact.java
javac -d . Basic\allmethod.java
